### ISSUE TITLE
Surveys have legacy references

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/kryptedauth#175]
Looks like we forgot to update some of these :P
```
[17/Feb/2019 05:04] ERROR [django.request:228] Internal Server Error: /engagement/surveys/view/all/
Traceback (most recent call last):
  File "/home/auth/production/kryptedauth/myvenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/auth/production/kryptedauth/myvenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/auth/production/kryptedauth/myvenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/auth/production/kryptedauth/myvenv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/auth/production/kryptedauth/myvenv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/auth/production/kryptedauth/app/modules/engagement/views/surveys.py", line 16, in dashboard
    guilds = set([survey.guild for survey in surveys if survey is not None])
  File "/home/auth/production/kryptedauth/app/modules/engagement/views/surveys.py", line 16, in <listcomp>
    guilds = set([survey.guild for survey in surveys if survey is not None])
AttributeError: 'Survey' object has no attribute 'guild'
```

**Comment by porowns** [comment]
This goes a little deeper, surveys need to be attached to a group on the model instead of a guild since we are no longer doing dependencies on external modules, e.g

`group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)`

**Comment by porowns** [comment]
Whoops I already did that in migration :P
